# Generated by Django 4.2.7 on 2025-10-01 13:51

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChessMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board",
                    models.JSONField(default=games.models.get_default_chess_board),
                ),
                ("current_player", models.CharField(default="white", max_length=5)),
                ("white_king_moved", models.BooleanField(default=False)),
                ("black_king_moved", models.BooleanField(default=False)),
                ("white_rook_king_moved", models.BooleanField(default=False)),
                ("white_rook_queen_moved", models.BooleanField(default=False)),
                ("black_rook_king_moved", models.BooleanField(default=False)),
                ("black_rook_queen_moved", models.BooleanField(default=False)),
                ("en_passant_target", models.CharField(default="", max_length=2)),
                ("halfmove_clock", models.IntegerField(default=0)),
                ("fullmove_number", models.IntegerField(default=1)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="games.match"
                    ),
                ),
            ],
        ),
    ]
