# Generated by Django 4.2.7 on 2025-10-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_chessmatch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chessmatch",
            old_name="halfmove_clock",
            new_name="move_count",
        ),
        migrations.RemoveField(
            model_name="chessmatch",
            name="black_king_moved",
        ),
        migrations.RemoveField(
            model_name="chessmatch",
            name="black_rook_king_moved",
        ),
        migrations.RemoveField(
            model_name="chessmatch",
            name="black_rook_queen_moved",
        ),
        migrations.RemoveField(
            model_name="chessmatch",
            name="en_passant_target",
        ),
        migrations.RemoveField(
            model_name="chessmatch",
            name="fullmove_number",
        ),
        migrations.RemoveField(
            model_name="chessmatch",
            name="white_king_moved",
        ),
        migrations.RemoveField(
            model_name="chessmatch",
            name="white_rook_king_moved",
        ),
        migrations.RemoveField(
            model_name="chessmatch",
            name="white_rook_queen_moved",
        ),
        migrations.AddField(
            model_name="chessmatch",
            name="fen",
            field=models.TextField(
                default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
            ),
        ),
    ]
